[workspace]
resolver = "3"
members = ["hawk", "hawk-python"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/melihakpinar/hawk"
authors = ["Mesut Melih Akpinar <mesutmelihakpinar@gmail.com>"]

[workspace.dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proptest = "1"
