"""Locates the fixture corpus.

The tests import ``hawk`` from wherever it is installed — the point of M3 step 10 is
that they exercise the wheel, not the working tree — but the corpus is data, and it is
read from the repository or from wherever ``HAWK_FIXTURES`` points. The clean-
environment check copies the corpus in without the Rust sources.
"""

from __future__ import annotations

import json
import os
import pathlib
from typing import Any

import pytest


def _fixture_directory() -> pathlib.Path:
    override = os.environ.get("HAWK_FIXTURES")
    if override:
        return pathlib.Path(override)
    return pathlib.Path(__file__).resolve().parents[2] / "tests" / "fixtures"


@pytest.fixture(scope="session")
def fixture_dir() -> pathlib.Path:
    directory = _fixture_directory()
    if not directory.is_dir():
        pytest.fail(
            f"fixture corpus not found at {directory}; set HAWK_FIXTURES to its location"
        )
    return directory


def load_corpus(directory: pathlib.Path) -> list[dict[str, Any]]:
    paths = sorted(p for p in directory.glob("*.json") if p.name != "rust-nll.json")
    if not paths:
        raise AssertionError(f"no fixtures in {directory}")
    return [json.loads(p.read_text()) for p in paths]


@pytest.fixture(scope="session")
def corpus(fixture_dir: pathlib.Path) -> list[dict[str, Any]]:
    return load_corpus(fixture_dir)


@pytest.fixture(scope="session")
def rust_manifest(fixture_dir: pathlib.Path) -> dict[tuple[str, str], int]:
    """Bit patterns of the negative log-likelihood as computed by Rust.

    Generated by ``cargo run --example dump_fixture_nll`` and kept current by
    ``hawk/tests/rust_nll_manifest.rs``.
    """
    path = fixture_dir / "rust-nll.json"
    if not path.is_file():
        pytest.fail(f"{path} is missing; regenerate with cargo run --example dump_fixture_nll")
    payload = json.loads(path.read_text())
    return {
        (entry["fixture"], entry["label"]): int(entry["negative_log_likelihood_bits"], 16)
        for entry in payload["entries"]
    }
