"""Type stubs for the compiled extension.

The extension is an implementation detail; callers use ``hawk.univariate`` and
``hawk.multivariate``. These stubs exist so ``mypy --strict`` can see through the
wrappers in those modules.
"""

import numpy as np
import numpy.typing as npt

class UnivariateParameters:
    def __init__(self, baseline: float, excitation: float, decay: float) -> None: ...
    @property
    def baseline(self) -> float: ...
    @property
    def excitation(self) -> float: ...
    @property
    def decay(self) -> float: ...
    def branching_ratio(self) -> float: ...
    def is_stationary(self) -> bool: ...
    def stationary_mean_intensity(self) -> float | None: ...

class UnivariateFit:
    @property
    def parameters(self) -> UnivariateParameters: ...
    @property
    def negative_log_likelihood(self) -> float: ...
    @property
    def iterations(self) -> int: ...
    @property
    def converged(self) -> bool: ...
    @property
    def gradient_norm(self) -> float: ...
    @property
    def objective_evaluations(self) -> int: ...
    @property
    def gradient_evaluations(self) -> int: ...
    def branching_ratio(self) -> float: ...
    def is_stationary(self) -> bool: ...

class MultivariateParameters:
    def __init__(
        self,
        baseline: npt.NDArray[np.float64],
        excitation: npt.NDArray[np.float64],
        decay: float,
    ) -> None: ...
    @property
    def baseline(self) -> npt.NDArray[np.float64]: ...
    @property
    def excitation(self) -> npt.NDArray[np.float64]: ...
    @property
    def decay(self) -> float: ...
    @property
    def dimension(self) -> int: ...
    def branching_ratio_spectral_radius(self) -> float: ...
    def is_stationary(self) -> bool: ...
    def stationary_mean_intensity(self) -> npt.NDArray[np.float64] | None: ...

class MultivariateFit:
    @property
    def parameters(self) -> MultivariateParameters: ...
    @property
    def negative_log_likelihood(self) -> float: ...
    @property
    def iterations(self) -> int: ...
    @property
    def converged(self) -> bool: ...
    @property
    def gradient_norm(self) -> float: ...
    @property
    def objective_evaluations(self) -> int: ...
    @property
    def gradient_evaluations(self) -> int: ...
    def branching_ratio_spectral_radius(self) -> float: ...
    def is_stationary(self) -> bool: ...

def univariate_negative_log_likelihood(
    parameters: UnivariateParameters,
    times: npt.NDArray[np.float64],
    horizon: float,
) -> float: ...
def univariate_negative_log_likelihood_and_gradient(
    parameters: UnivariateParameters,
    times: npt.NDArray[np.float64],
    horizon: float,
) -> tuple[float, float, float, float]: ...
def univariate_simulate(
    parameters: UnivariateParameters, horizon: float, seed: int
) -> npt.NDArray[np.float64]: ...
def univariate_fit(
    times: npt.NDArray[np.float64], horizon: float
) -> UnivariateFit: ...
def multivariate_negative_log_likelihood(
    parameters: MultivariateParameters,
    events: list[npt.NDArray[np.float64]],
    horizon: float,
) -> float: ...
def multivariate_negative_log_likelihood_and_gradient(
    parameters: MultivariateParameters,
    events: list[npt.NDArray[np.float64]],
    horizon: float,
) -> tuple[float, npt.NDArray[np.float64], npt.NDArray[np.float64], float]: ...
def multivariate_compensator_at_events(
    parameters: MultivariateParameters,
    events: list[npt.NDArray[np.float64]],
    horizon: float,
) -> list[npt.NDArray[np.float64]]: ...
def multivariate_simulate(
    parameters: MultivariateParameters, horizon: float, seed: int
) -> list[npt.NDArray[np.float64]]: ...
def multivariate_fit(
    events: list[npt.NDArray[np.float64]], horizon: float
) -> MultivariateFit: ...
